Fix build errors
Fixes the following build errors:
- `src/pwa.ts(1,28): error TS2307: Cannot find module 'virtual:pwa-register' or its corresponding type declarations.`
- `bun install failed to complete: ProcessIOError("Process killed due to timeout")`
- `sh: 1: vite: not found